import 'dart:typed_data';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:junglengine/audio/audio_clip.dart';
import 'package:junglengine/audio/wav.dart';

void main() {
  group('wav', () {
    test('round trips stereo audio within 16 bit resolution', () {
      final samples = Float32List.fromList([
        0.0, 0.5, -0.5, 0.25, 0.999, -0.999, 0.125, -0.125,
      ]);
      final bytes = encodeWav(samples, sampleRate: 44100, channels: 2);
      final clip = decodeWav(bytes);

      expect(clip.channels, 2);
      expect(clip.sampleRate, 44100);
      expect(clip.frames, 4);
      for (var i = 0; i < samples.length; i++) {
        // int16 quantisation, plus the 32767/32768 scale asymmetry.
        expect(clip.samples[i], closeTo(samples[i], 1e-4));
      }
    });

    test('rejects something that is not a wav', () {
      expect(
        () => decodeWav(Uint8List.fromList(List.filled(64, 7))),
        throwsA(isA<WavFormatException>()),
      );
    });

    test('reads the bundled break generated by tool/make_break.dart', () async {
      TestWidgetsFlutterBinding.ensureInitialized();
      final data = await rootBundle.load(
        'assets/breaks/hawkstreak_amenish_170.wav',
      );
      final clip = decodeWav(data.buffer.asUint8List());
      expect(clip.channels, 2);
      expect(clip.sampleRate, 44100);
      // One bar at 170 BPM.
      expect(clip.frames, closeTo(44100 * 4 * 60 / 170, 2));
    });
  });

  group('AudioClip', () {
    test('mono is widened to stereo', () {
      final clip = AudioClip(
        samples: Float32List.fromList([0.5, -0.5]),
        channels: 1,
        sampleRate: 44100,
      ).toStereo();
      expect(clip.channels, 2);
      expect(clip.samples, [0.5, 0.5, -0.5, -0.5]);
    });

    test('resampling halves the frame count when the rate halves', () {
      final clip = AudioClip.silent(frames: 1000, sampleRate: 44100)
          .resampledTo(22050);
      expect(clip.sampleRate, 22050);
      expect(clip.frames, 500);
    });

    test('normalising brings the peak to the target', () {
      final clip = AudioClip(
        samples: Float32List.fromList([0.1, -0.2, 0.05, 0.0]),
        channels: 2,
        sampleRate: 44100,
      ).normalized(target: 0.9);
      var peak = 0.0;
      for (final s in clip.samples) {
        if (s.abs() > peak) peak = s.abs();
      }
      expect(peak, closeTo(0.9, 1e-6));
    });
  });
}
